In [5]:
# My CA1 in Data Exploration and Preparation

In [7]:
# Start importing libraries (they store the specific functions we will need)
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("Smart_Home_Energy.csv")

df.head()

,dwelling_type,heating_type,tariff_type,occupants,floor_area_m2,avg_outdoor_temp_c,avg_daily_use_kwh,monthly_bill_eur
0,Semi-detached,Heat Pump,Standard,2,173.7,5.4,18.84,176.72
1,Detached,Gas,Smart,1,131.8,11.1,9.95,96.82
2,Semi-detached,Electric,Smart,4,146.5,12.6,19.54,239.75
3,Semi-detached,Oil,Smart,6,72.4,11.7,14.34,139.45
4,Semi-detached,Heat Pump,Smart,3,170.2,9.2,14.73,148.39

In [14]:
# Understand the dataset
print("Number of observations:", df.shape[0]) # observations = rows
print("Number of variables:", df.shape[1]) # variables = columns

# Dimensions 
print("Dimensions:", df.shape) # observations and variables 

# Finding the variables/columns names 
print("Column names:")
print(df.columns.tolist())

Number of observations: 5507
Number of variables: 8
Dimensions: (5507, 8)
Column names:
['dwelling_type', 'heating_type', 'tariff_type', 'occupants', 'floor_area_m2', 'avg_outdoor_temp_c', 'avg_daily_use_kwh', 'monthly_bill_eur']

In [10]:
# Detailed information of the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5507 entries, 0 to 5506
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   dwelling_type       5507 non-null   str
 1   heating_type        5462 non-null   str
 2   tariff_type         5416 non-null   str
 3   occupants           5507 non-null   int64
 4   floor_area_m2       5388 non-null   float64
 5   avg_outdoor_temp_c  5373 non-null   float64
 6   avg_daily_use_kwh   5450 non-null   float64
 7   monthly_bill_eur    5441 non-null   float64
dtypes: float64(4), int64(1), str(3)
memory usage: 467.0 KB

In [11]:
# Details of statistics of the dataset
df.describe()

,occupants,floor_area_m2,avg_outdoor_temp_c,avg_daily_use_kwh,monthly_bill_eur
count,5507.000000,5388.000000,5373.000000,5450.000000,5441.000000
mean,3.617941,126.094321,10.292779,19.389418,196.922007
std,1.859492,78.360763,5.432457,16.425565,190.919214
min,1.000000,30.300000,-27.900000,5.000000,40.000000
25%,2.000000,86.800000,7.100000,13.490000,122.600000
50%,4.000000,116.200000,10.300000,17.370000,169.050000
75%,5.000000,151.700000,13.500000,21.280000,228.820000
max,20.000000,946.700000,46.000000,219.420000,2788.410000

In [15]:
# Find the data types
print("\nData types:")
print(df.dtypes)

Data types:
dwelling_type             str
heating_type              str
tariff_type               str
occupants               int64
floor_area_m2         float64
avg_outdoor_temp_c    float64
avg_daily_use_kwh     float64
monthly_bill_eur      float64
dtype: object

In [16]:
# Finding duplicated values
print(df.duplicated().sum())

157

In [18]:
# Remove duplicates creating a copy and not changing the original file
df_analysis = df.drop_duplicates().copy()

In [19]:
# Check the original number of rows and after removing the duplicates
print("Original number of rows:", len(df))
print("Rows after removing duplicates:", len(df_analysis))

Original number of rows: 5507
Rows after removing duplicates: 5350

In [20]:
# Finding missing values 
df.isnull().sum()

dwelling_type           0
heating_type           45
tariff_type            91
occupants               0
floor_area_m2         119
avg_outdoor_temp_c    134
avg_daily_use_kwh      57
monthly_bill_eur       66
dtype: int64

In [23]:
# Specifying categorical or numerical variables
categorical_columns = ["dwelling_type", "heating_type", "tariff_type"] 
numerical_columns = ["occupants", "floor_area_m2", "avg_outdoor_temp_c", "avg_daily_use_kwh", "monthly_bill_eur"]
print("\nCategorical variables:") 
print(categorical_columns)
print("\nNumerical variables:")
print(numerical_columns)

Categorical variables:
['dwelling_type', 'heating_type', 'tariff_type']

Numerical variables:
['occupants', 'floor_area_m2', 'avg_outdoor_temp_c', 'avg_daily_use_kwh', 'monthly_bill_eur']

In [28]:
# Replace missing values in categorical columns with mode 
categorical_columns = df.select_dtypes(include = ["object", "str"]).columns

for column in categorical_columns:
    df[column] = df[column].fillna(
        df[column].mode()[0]
    )

# Check if missing values have been filled
print(df.isnull().sum())

dwelling_type           0
heating_type            0
tariff_type             0
occupants               0
floor_area_m2         119
avg_outdoor_temp_c    134
avg_daily_use_kwh      57
monthly_bill_eur       66
dtype: int64

In [33]:
# Replace missing numerical values 

df["floor_area_m2"] = df["floor_area_m2"].fillna(
    df["floor_area_m2"].median()
)

df["avg_outdoor_temp_c"] = df["avg_outdoor_temp_c"].fillna(
    df["avg_outdoor_temp_c"].median()
)

df["avg_daily_use_kwh"] = df["avg_daily_use_kwh"].fillna(
    df["avg_daily_use_kwh"].median()
)

df["monthly_bill_eur"] = df["monthly_bill_eur"].fillna(
    df["monthly_bill_eur"].median()
)

# Check if missing values have been filled
print(df.isnull().sum())

dwelling_type         0
heating_type          0
tariff_type           0
occupants             0
floor_area_m2         0
avg_outdoor_temp_c    0
avg_daily_use_kwh     0
monthly_bill_eur      0
dtype: int64

In [34]:
# Detailed descriptive statistics (rounding to get a smaller number and easier to visualize)

print("\nDescriptive Statistics:")

df_analysis[numerical_columns].describe().round(2)

Descriptive Statistics:

,occupants,floor_area_m2,avg_outdoor_temp_c,avg_daily_use_kwh,monthly_bill_eur
count,5350.00,5235.00,5221.00,5296.00,5286.00
mean,3.62,125.82,10.30,19.40,197.63
std,1.86,76.88,5.45,16.43,192.86
min,1.00,30.30,-27.90,5.00,40.00
25%,2.00,87.05,7.10,13.52,122.78
50%,4.00,116.20,10.30,17.39,169.48
75%,5.00,151.50,13.50,21.29,229.38
max,20.00,946.70,46.00,219.42,2788.41